<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- nuget properties-->
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>CSharpExt.Core</PackageId>
    <Version>1.0.0</Version>
    <Authors>Dio Liew</Authors>
    <Company>Venture GES Manufacturing Services(M) Sdn Bhd</Company>
    <Description>An extension to C# to ease functional code style.</Description>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>IDE1006</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>IDE1006</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LanguageExt.Core" Version="5.0.0-beta-77" />
  </ItemGroup>
</Project>